/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as SubmissionsIdImport } from './routes/submissions/$id'
import { Route as LayoutSubmissionsImport } from './routes/_layout.submissions'
import { Route as LayoutProblemsImport } from './routes/_layout.problems'
import { Route as ProblemsIdIndexImport } from './routes/problems/$id/index'
import { Route as ProblemsIdProblemLayoutImport } from './routes/problems/$id/_problemLayout'
import { Route as ProblemsIdProblemLayoutDescImport } from './routes/problems/$id/_problemLayout.desc'
import { Route as ProblemsIdProblemLayoutSubmissionsIndexImport } from './routes/problems/$id/_problemLayout.submissions/index'
import { Route as ProblemsIdProblemLayoutSubmissionsIdImport } from './routes/problems/$id/_problemLayout.submissions/$id'

// Create Virtual Routes

const ProblemsIdImport = createFileRoute('/problems/$id')()

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProblemsIdRoute = ProblemsIdImport.update({
  id: '/problems/$id',
  path: '/problems/$id',
  getParentRoute: () => rootRoute,
} as any)

const SubmissionsIdRoute = SubmissionsIdImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => rootRoute,
} as any)

const LayoutSubmissionsRoute = LayoutSubmissionsImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProblemsRoute = LayoutProblemsImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => LayoutRoute,
} as any)

const ProblemsIdIndexRoute = ProblemsIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsIdRoute,
} as any)

const ProblemsIdProblemLayoutRoute = ProblemsIdProblemLayoutImport.update({
  id: '/_problemLayout',
  getParentRoute: () => ProblemsIdRoute,
} as any)

const ProblemsIdProblemLayoutDescRoute =
  ProblemsIdProblemLayoutDescImport.update({
    id: '/desc',
    path: '/desc',
    getParentRoute: () => ProblemsIdProblemLayoutRoute,
  } as any)

const ProblemsIdProblemLayoutSubmissionsIndexRoute =
  ProblemsIdProblemLayoutSubmissionsIndexImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => ProblemsIdProblemLayoutRoute,
  } as any)

const ProblemsIdProblemLayoutSubmissionsIdRoute =
  ProblemsIdProblemLayoutSubmissionsIdImport.update({
    id: '/submissions/$id',
    path: '/submissions/$id',
    getParentRoute: () => ProblemsIdProblemLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_layout/problems': {
      id: '/_layout/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof LayoutProblemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/submissions': {
      id: '/_layout/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof LayoutSubmissionsImport
      parentRoute: typeof LayoutImport
    }
    '/submissions/$id': {
      id: '/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/submissions/$id'
      preLoaderRoute: typeof SubmissionsIdImport
      parentRoute: typeof rootRoute
    }
    '/problems/$id': {
      id: '/problems/$id'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdImport
      parentRoute: typeof rootRoute
    }
    '/problems/$id/_problemLayout': {
      id: '/problems/$id/_problemLayout'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof ProblemsIdProblemLayoutImport
      parentRoute: typeof ProblemsIdRoute
    }
    '/problems/$id/': {
      id: '/problems/$id/'
      path: '/'
      fullPath: '/problems/$id/'
      preLoaderRoute: typeof ProblemsIdIndexImport
      parentRoute: typeof ProblemsIdImport
    }
    '/problems/$id/_problemLayout/desc': {
      id: '/problems/$id/_problemLayout/desc'
      path: '/desc'
      fullPath: '/problems/$id/desc'
      preLoaderRoute: typeof ProblemsIdProblemLayoutDescImport
      parentRoute: typeof ProblemsIdProblemLayoutImport
    }
    '/problems/$id/_problemLayout/submissions/$id': {
      id: '/problems/$id/_problemLayout/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/problems/$id/submissions/$id'
      preLoaderRoute: typeof ProblemsIdProblemLayoutSubmissionsIdImport
      parentRoute: typeof ProblemsIdProblemLayoutImport
    }
    '/problems/$id/_problemLayout/submissions/': {
      id: '/problems/$id/_problemLayout/submissions/'
      path: '/submissions'
      fullPath: '/problems/$id/submissions'
      preLoaderRoute: typeof ProblemsIdProblemLayoutSubmissionsIndexImport
      parentRoute: typeof ProblemsIdProblemLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutProblemsRoute: typeof LayoutProblemsRoute
  LayoutSubmissionsRoute: typeof LayoutSubmissionsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProblemsRoute: LayoutProblemsRoute,
  LayoutSubmissionsRoute: LayoutSubmissionsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ProblemsIdProblemLayoutRouteChildren {
  ProblemsIdProblemLayoutDescRoute: typeof ProblemsIdProblemLayoutDescRoute
  ProblemsIdProblemLayoutSubmissionsIdRoute: typeof ProblemsIdProblemLayoutSubmissionsIdRoute
  ProblemsIdProblemLayoutSubmissionsIndexRoute: typeof ProblemsIdProblemLayoutSubmissionsIndexRoute
}

const ProblemsIdProblemLayoutRouteChildren: ProblemsIdProblemLayoutRouteChildren =
  {
    ProblemsIdProblemLayoutDescRoute: ProblemsIdProblemLayoutDescRoute,
    ProblemsIdProblemLayoutSubmissionsIdRoute:
      ProblemsIdProblemLayoutSubmissionsIdRoute,
    ProblemsIdProblemLayoutSubmissionsIndexRoute:
      ProblemsIdProblemLayoutSubmissionsIndexRoute,
  }

const ProblemsIdProblemLayoutRouteWithChildren =
  ProblemsIdProblemLayoutRoute._addFileChildren(
    ProblemsIdProblemLayoutRouteChildren,
  )

interface ProblemsIdRouteChildren {
  ProblemsIdProblemLayoutRoute: typeof ProblemsIdProblemLayoutRouteWithChildren
  ProblemsIdIndexRoute: typeof ProblemsIdIndexRoute
}

const ProblemsIdRouteChildren: ProblemsIdRouteChildren = {
  ProblemsIdProblemLayoutRoute: ProblemsIdProblemLayoutRouteWithChildren,
  ProblemsIdIndexRoute: ProblemsIdIndexRoute,
}

const ProblemsIdRouteWithChildren = ProblemsIdRoute._addFileChildren(
  ProblemsIdRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/problems': typeof LayoutProblemsRoute
  '/submissions': typeof LayoutSubmissionsRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/problems/$id': typeof ProblemsIdProblemLayoutRouteWithChildren
  '/problems/$id/': typeof ProblemsIdIndexRoute
  '/problems/$id/desc': typeof ProblemsIdProblemLayoutDescRoute
  '/problems/$id/submissions/$id': typeof ProblemsIdProblemLayoutSubmissionsIdRoute
  '/problems/$id/submissions': typeof ProblemsIdProblemLayoutSubmissionsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/problems': typeof LayoutProblemsRoute
  '/submissions': typeof LayoutSubmissionsRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/problems/$id': typeof ProblemsIdIndexRoute
  '/problems/$id/desc': typeof ProblemsIdProblemLayoutDescRoute
  '/problems/$id/submissions/$id': typeof ProblemsIdProblemLayoutSubmissionsIdRoute
  '/problems/$id/submissions': typeof ProblemsIdProblemLayoutSubmissionsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_layout/problems': typeof LayoutProblemsRoute
  '/_layout/submissions': typeof LayoutSubmissionsRoute
  '/submissions/$id': typeof SubmissionsIdRoute
  '/problems/$id': typeof ProblemsIdRouteWithChildren
  '/problems/$id/_problemLayout': typeof ProblemsIdProblemLayoutRouteWithChildren
  '/problems/$id/': typeof ProblemsIdIndexRoute
  '/problems/$id/_problemLayout/desc': typeof ProblemsIdProblemLayoutDescRoute
  '/problems/$id/_problemLayout/submissions/$id': typeof ProblemsIdProblemLayoutSubmissionsIdRoute
  '/problems/$id/_problemLayout/submissions/': typeof ProblemsIdProblemLayoutSubmissionsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/problems'
    | '/submissions'
    | '/submissions/$id'
    | '/problems/$id'
    | '/problems/$id/'
    | '/problems/$id/desc'
    | '/problems/$id/submissions/$id'
    | '/problems/$id/submissions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/register'
    | '/problems'
    | '/submissions'
    | '/submissions/$id'
    | '/problems/$id'
    | '/problems/$id/desc'
    | '/problems/$id/submissions/$id'
    | '/problems/$id/submissions'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/register'
    | '/_layout/problems'
    | '/_layout/submissions'
    | '/submissions/$id'
    | '/problems/$id'
    | '/problems/$id/_problemLayout'
    | '/problems/$id/'
    | '/problems/$id/_problemLayout/desc'
    | '/problems/$id/_problemLayout/submissions/$id'
    | '/problems/$id/_problemLayout/submissions/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SubmissionsIdRoute: typeof SubmissionsIdRoute
  ProblemsIdRoute: typeof ProblemsIdRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SubmissionsIdRoute: SubmissionsIdRoute,
  ProblemsIdRoute: ProblemsIdRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/login",
        "/register",
        "/submissions/$id",
        "/problems/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/problems",
        "/_layout/submissions"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_layout/problems": {
      "filePath": "_layout.problems.tsx",
      "parent": "/_layout"
    },
    "/_layout/submissions": {
      "filePath": "_layout.submissions.tsx",
      "parent": "/_layout"
    },
    "/submissions/$id": {
      "filePath": "submissions/$id.tsx"
    },
    "/problems/$id": {
      "filePath": "problems/$id",
      "children": [
        "/problems/$id/_problemLayout",
        "/problems/$id/"
      ]
    },
    "/problems/$id/_problemLayout": {
      "filePath": "problems/$id/_problemLayout.tsx",
      "parent": "/problems/$id",
      "children": [
        "/problems/$id/_problemLayout/desc",
        "/problems/$id/_problemLayout/submissions/$id",
        "/problems/$id/_problemLayout/submissions/"
      ]
    },
    "/problems/$id/": {
      "filePath": "problems/$id/index.tsx",
      "parent": "/problems/$id"
    },
    "/problems/$id/_problemLayout/desc": {
      "filePath": "problems/$id/_problemLayout.desc.tsx",
      "parent": "/problems/$id/_problemLayout"
    },
    "/problems/$id/_problemLayout/submissions/$id": {
      "filePath": "problems/$id/_problemLayout.submissions/$id.tsx",
      "parent": "/problems/$id/_problemLayout"
    },
    "/problems/$id/_problemLayout/submissions/": {
      "filePath": "problems/$id/_problemLayout.submissions/index.tsx",
      "parent": "/problems/$id/_problemLayout"
    }
  }
}
ROUTE_MANIFEST_END */
